package frc.robot.subsystems.drive;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.sim.CANcoderSimState;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.sim.Pigeon2SimState;
import com.ctre.phoenix6.sim.TalonFXSimState;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.constants.drive.DrivetrainConstants;
import frc.robot.constants.drive.DrivetrainConstants.TunerSwerveDrivetrain;
import org.ironmaple.simulation.SimulatedArena;
import org.ironmaple.simulation.drivesims.AbstractDriveTrainSimulation;
import org.ironmaple.simulation.drivesims.COTS;
import org.ironmaple.simulation.drivesims.SwerveDriveSimulation;
import org.ironmaple.simulation.drivesims.SwerveModuleSimulation;
import org.ironmaple.simulation.drivesims.configs.DriveTrainSimulationConfig;
import org.ironmaple.simulation.drivesims.configs.SwerveModuleSimulationConfig;
import org.ironmaple.simulation.motorsims.SimulatedMotorController;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
	/* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
	private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
	/* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
	private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
	/* Keep track if we've ever applied the operator perspective before or not */
	private boolean m_hasAppliedOperatorPerspective = false;
	private boolean m_shouldFlipAutoPath = false;

	/** Swerve request to apply during robot-centric path following */
	private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();
	private final SwerveRequest.Idle m_idleRequest = new SwerveRequest.Idle();

	/* Swerve requests to apply during SysId characterization */
	private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
	private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
	private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

	private final Telemetry telemetry = new Telemetry(DrivetrainConstants.kSpeedAt12Volts.in(MetersPerSecond));
	private final SwerveModuleConstants<?, ?, ?>[] m_moduleConstants;
	private final SwerveDriveSimulation m_mapleDriveSimulation;
	private final SimulatedMotorController.GenericMotorController[] m_mapleDriveControllers;
	private final SimulatedMotorController.GenericMotorController[] m_mapleSteerControllers;

	/*
	 * SysId routine for characterizing translation. This is used to find PID gains
	 * for the drive motors.
	 */
	private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(new SysIdRoutine.Config(null, // Use default
																											// ramp rate
																											// (1 V/s)
			Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
			null, // Use default timeout (10 s)
			// Log state with SignalLogger class
			state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
			new SysIdRoutine.Mechanism(output -> setControl(m_translationCharacterization.withVolts(output)), null,
					this));

	/*
	 * SysId routine for characterizing steer. This is used to find PID gains for
	 * the steer motors.
	 */
	private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(new SysIdRoutine.Config(null, // Use default ramp
																									// rate (1 V/s)
			Volts.of(7), // Use dynamic voltage of 7 V
			null, // Use default timeout (10 s)
			// Log state with SignalLogger class
			state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
			new SysIdRoutine.Mechanism(volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

	/*
	 * SysId routine for characterizing rotation. This is used to find PID gains for
	 * the FieldCentricFacingAngle HeadingController. See the documentation of
	 * SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
	 */
	private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(new SysIdRoutine.Config(
			/* This is in radians per second², but SysId only supports "volts per second" */
			Volts.of(Math.PI / 6).per(Second),
			/* This is in radians per second, but SysId only supports "volts" */
			Volts.of(Math.PI), null, // Use default timeout (10 s)
			// Log state with SignalLogger class
			state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
			new SysIdRoutine.Mechanism(output -> {
				/* output is actually radians per second, but SysId only supports "volts" */
				setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
				/* also log the requested output for SysId */
				SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
			}, null, this));

	/* The SysId routine to test */
	private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

	/**
	 * Constructs a CTRE SwerveDrivetrain using the specified constants.
	 * <p>
	 * This constructs the underlying hardware devices, so users should not
	 * construct the devices themselves. If they need the devices, they can access
	 * them through getters in the classes.
	 *
	 * @param drivetrainConstants
	 *            Drivetrain-wide constants for the swerve drive
	 * @param modules
	 *            Constants for each specific module
	 */
	public CommandSwerveDrivetrain(SwerveDrivetrainConstants drivetrainConstants,
			SwerveModuleConstants<?, ?, ?>... modules) {
		super(drivetrainConstants, modules);
		m_moduleConstants = modules.clone();
		m_mapleDriveSimulation = createMapleDriveSimulation();
		m_mapleDriveControllers = createMapleDriveControllers(m_mapleDriveSimulation);
		m_mapleSteerControllers = createMapleSteerControllers(m_mapleDriveSimulation);
		seedDefaultSimulationPose();
		configureAutoBuilder();
	}

	/**
	 * Constructs a CTRE SwerveDrivetrain using the specified constants.
	 * <p>
	 * This constructs the underlying hardware devices, so users should not
	 * construct the devices themselves. If they need the devices, they can access
	 * them through getters in the classes.
	 *
	 * @param drivetrainConstants
	 *            Drivetrain-wide constants for the swerve drive
	 * @param odometryUpdateFrequency
	 *            The frequency to run the odometry loop. If unspecified or set to 0
	 *            Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
	 * @param modules
	 *            Constants for each specific module
	 */
	public CommandSwerveDrivetrain(SwerveDrivetrainConstants drivetrainConstants, double odometryUpdateFrequency,
			SwerveModuleConstants<?, ?, ?>... modules) {
		super(drivetrainConstants, odometryUpdateFrequency, modules);
		m_moduleConstants = modules.clone();
		m_mapleDriveSimulation = createMapleDriveSimulation();
		m_mapleDriveControllers = createMapleDriveControllers(m_mapleDriveSimulation);
		m_mapleSteerControllers = createMapleSteerControllers(m_mapleDriveSimulation);
		seedDefaultSimulationPose();
		configureAutoBuilder();
	}

	/**
	 * Constructs a CTRE SwerveDrivetrain using the specified constants.
	 * <p>
	 * This constructs the underlying hardware devices, so users should not
	 * construct the devices themselves. If they need the devices, they can access
	 * them through getters in the classes.
	 *
	 * @param drivetrainConstants
	 *            Drivetrain-wide constants for the swerve drive
	 * @param odometryUpdateFrequency
	 *            The frequency to run the odometry loop. If unspecified or set to 0
	 *            Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
	 * @param odometryStandardDeviation
	 *            The standard deviation for odometry calculation in the form [x, y,
	 *            theta]ᵀ, with units in meters and radians
	 * @param visionStandardDeviation
	 *            The standard deviation for vision calculation in the form [x, y,
	 *            theta]ᵀ, with units in meters and radians
	 * @param modules
	 *            Constants for each specific module
	 */
	public CommandSwerveDrivetrain(SwerveDrivetrainConstants drivetrainConstants, double odometryUpdateFrequency,
			Matrix<N3, N1> odometryStandardDeviation, Matrix<N3, N1> visionStandardDeviation,
			SwerveModuleConstants<?, ?, ?>... modules) {
		super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
				modules);
		m_moduleConstants = modules.clone();
		m_mapleDriveSimulation = createMapleDriveSimulation();
		m_mapleDriveControllers = createMapleDriveControllers(m_mapleDriveSimulation);
		m_mapleSteerControllers = createMapleSteerControllers(m_mapleDriveSimulation);
		seedDefaultSimulationPose();
		configureAutoBuilder();
	}

	private void configureAutoBuilder() {
		try {
			var config = RobotConfig.fromGUISettings();
			AutoBuilder.configure(() -> getState().Pose, // Supplier of current robot pose
					this::resetPose, // Consumer for seeding pose against auto
					() -> getState().Speeds, // Supplier of current robot speeds
					// Consumer of ChassisSpeeds and feedforwards to drive the robot
					(speeds, feedforwards) -> {
						telemetry.logAutoCommandedSpeeds(speeds);
						setControl(m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020)));
					}, new PPHolonomicDriveController(
							// PID constants for translation
							new PIDConstants(10, 0, 0),
							// PID constants for rotation
							new PIDConstants(7, 0, 0)),
					config,
					// Assume the path needs to be flipped for Red vs Blue, this is normally the
					// case
					this::shouldFlipAutoPath, this // Subsystem for requirements
			);
		} catch (Exception ex) {
			DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder",
					ex.getStackTrace());
		}
	}

	/**
	 * Returns a command that applies the specified control request to this swerve
	 * drivetrain.
	 *
	 * @param request
	 *            Function returning the request to apply
	 * @return Command to run
	 */
	public Command applyRequest(Supplier<SwerveRequest> request) {
		return run(() -> this.setControl(request.get()));
	}

	public void stop() {
		setControl(m_idleRequest);
	}

	/**
	 * Runs the SysId Quasistatic test in the given direction for the routine
	 * specified by {@link #m_sysIdRoutineToApply}.
	 *
	 * @param direction
	 *            Direction of the SysId Quasistatic test
	 * @return Command to run
	 */
	public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
		return m_sysIdRoutineToApply.quasistatic(direction);
	}

	/**
	 * Runs the SysId Dynamic test in the given direction for the routine specified
	 * by {@link #m_sysIdRoutineToApply}.
	 *
	 * @param direction
	 *            Direction of the SysId Dynamic test
	 * @return Command to run
	 */
	public Command sysIdDynamic(SysIdRoutine.Direction direction) {
		return m_sysIdRoutineToApply.dynamic(direction);
	}

	@Override
	public void periodic() {
		if (m_mapleDriveSimulation != null) {
			syncPhoenixSimStateFromMaple();
			applyPhoenixOutputsToMaple();
			SimulatedArena.getInstance().simulationPeriodic();
			syncPhoenixSimStateFromMaple();
		}

		var state = getState();

		/*
		 * Periodically try to apply the operator perspective. If we haven't applied the
		 * operator perspective before, then we should apply it regardless of DS state.
		 * This allows us to correct the perspective in case the robot code restarts
		 * mid-match. Otherwise, only check and apply the operator perspective if the DS
		 * is disabled. This ensures driving behavior doesn't change until an explicit
		 * disable event occurs during testing.
		 */
		if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
			updateAllianceState();
		}
		telemetry.telemeterize(state, getPhysicsPose());

	}

	public AbstractDriveTrainSimulation getSimulation() {
		return m_mapleDriveSimulation;
	}

	public Pose2d getPhysicsPose() {
		return m_mapleDriveSimulation != null ? m_mapleDriveSimulation.getSimulatedDriveTrainPose() : getState().Pose;
	}

	public ChassisSpeeds getPhysicsSpeeds() {
		return m_mapleDriveSimulation != null
				? m_mapleDriveSimulation.getDriveTrainSimulatedChassisSpeedsRobotRelative()
				: getState().Speeds;
	}

	public boolean shouldFlipAutoPath() {
		updateAllianceState();
		return m_shouldFlipAutoPath;
	}

	private void updateAllianceState() {
		DriverStation.getAlliance().ifPresent(allianceColor -> {
			m_shouldFlipAutoPath = allianceColor == Alliance.Red;
			setOperatorPerspectiveForward(
					allianceColor == Alliance.Red ? kRedAlliancePerspectiveRotation : kBlueAlliancePerspectiveRotation);
			m_hasAppliedOperatorPerspective = true;
		});
	}

	public void resetSimulationPoseOnly(Pose2d pose) {
		if (m_mapleDriveSimulation == null) {
			return;
		}

		teleportMapleSimulation(pose);
		syncPhoenixSimStateFromMaple();
	}

	/**
	 * Adds a vision measurement to the Kalman Filter. This will correct the
	 * odometry pose estimate while still accounting for measurement noise.
	 *
	 * @param visionRobotPoseMeters
	 *            The pose of the robot as measured by the vision camera.
	 * @param timestampSeconds
	 *            The timestamp of the vision measurement in seconds.
	 */
	@Override
	public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
		super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
	}

	/**
	 * Adds a vision measurement to the Kalman Filter. This will correct the
	 * odometry pose estimate while still accounting for measurement noise.
	 * <p>
	 * Note that the vision measurement standard deviations passed into this method
	 * will continue to apply to future measurements until a subsequent call to
	 * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
	 *
	 * @param visionRobotPoseMeters
	 *            The pose of the robot as measured by the vision camera.
	 * @param timestampSeconds
	 *            The timestamp of the vision measurement in seconds.
	 * @param visionMeasurementStdDevs
	 *            Standard deviations of the vision pose measurement in the form [x,
	 *            y, theta]ᵀ, with units in meters and radians.
	 */
	@Override
	public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds,
			Matrix<N3, N1> visionMeasurementStdDevs) {
		super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
				visionMeasurementStdDevs);
	}

	/**
	 * Return the pose at a given timestamp, if the buffer is not empty.
	 *
	 * @param timestampSeconds
	 *            The timestamp of the pose in seconds.
	 * @return The pose at the given timestamp (or Optional.empty() if the buffer is
	 *         empty).
	 */
	@Override
	public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
		return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
	}

	@Override
	public void resetPose(Pose2d pose) {
		if (m_mapleDriveSimulation == null) {
			super.resetPose(pose);
			return;
		}

		teleportMapleSimulation(pose);
		syncPhoenixSimStateFromMaple();
		super.resetPose(pose);
		syncPhoenixSimStateFromMaple();
	}

	@Override
	public void resetTranslation(edu.wpi.first.math.geometry.Translation2d translation) {
		if (m_mapleDriveSimulation == null) {
			super.resetTranslation(translation);
			return;
		}

		Pose2d currentPose = m_mapleDriveSimulation.getSimulatedDriveTrainPose();
		teleportMapleSimulation(new Pose2d(translation, currentPose.getRotation()));
		syncPhoenixSimStateFromMaple();
		super.resetTranslation(translation);
		syncPhoenixSimStateFromMaple();
	}

	@Override
	public void resetRotation(Rotation2d rotation) {
		if (m_mapleDriveSimulation == null) {
			super.resetRotation(rotation);
			return;
		}

		Pose2d currentPose = m_mapleDriveSimulation.getSimulatedDriveTrainPose();
		teleportMapleSimulation(new Pose2d(currentPose.getTranslation(), rotation));
		syncPhoenixSimStateFromMaple();
		super.resetRotation(rotation);
		syncPhoenixSimStateFromMaple();
	}

	private SwerveDriveSimulation createMapleDriveSimulation() {
		if (!Utils.isSimulation()) {
			return null;
		}

		SwerveDriveSimulation simulation = new SwerveDriveSimulation(DrivetrainConstants.SIMULATION_CONFIG,
				getState().Pose);
		SimulatedArena.getInstance().addDriveTrainSimulation(simulation);
		SimulatedArena.getInstance().addCustomSimulation(subTickNum -> updatePhoenixSimSignals());
		configurePhoenixSimDevices();
		return simulation;
	}

	private void seedDefaultSimulationPose() {
		if (m_mapleDriveSimulation != null) {
			resetPose(getDefaultSimulationPose());
		}
	}

	private void teleportMapleSimulation(Pose2d pose) {
		m_mapleDriveSimulation.setSimulationWorldPose(pose);
		m_mapleDriveSimulation.setRobotSpeeds(new ChassisSpeeds());
		m_mapleDriveSimulation.getGyroSimulation().setRotation(pose.getRotation());
		Timer.delay(DrivetrainConstants.kSimResetSettleSeconds);
	}

	private Pose2d getDefaultSimulationPose() {
		// Exact field center intersects the center fuel stack in Rebuilt, which causes
		// immediate collision jitter at sim startup.
		return new Pose2d(DrivetrainConstants.kSimFieldLengthMeters / 2.0,
				DrivetrainConstants.kSimFieldWidthMeters / 2.0, Rotation2d.kZero);
	}

	private SwerveModuleSimulationConfig createSwerveModuleSimulationFactory() {
		SwerveModuleConstants<?, ?, ?> module = m_moduleConstants[0];
		DCMotor driveMotorModel = DCMotor.getKrakenX60Foc(1);
		double calibratedWheelRadiusMeters = DrivetrainConstants.kSpeedAt12Volts.in(MetersPerSecond)
				/ (driveMotorModel.freeSpeedRadPerSec / module.DriveMotorGearRatio);
		return new SwerveModuleSimulationConfig(driveMotorModel, DCMotor.getKrakenX60Foc(1), module.DriveMotorGearRatio,
				module.SteerMotorGearRatio, Volts.of(module.DriveFrictionVoltage),
				Volts.of(module.SteerFrictionVoltage), Meters.of(calibratedWheelRadiusMeters),
				KilogramSquareMeters.of(module.SteerInertia), DrivetrainConstants.kSimWheelCoefficientOfFriction);
	}

	private SimulatedMotorController.GenericMotorController[] createMapleDriveControllers(
			SwerveDriveSimulation simulation) {
		if (simulation == null) {
			return null;
		}

		SwerveModuleSimulation[] mapleModules = simulation.getModules();
		SimulatedMotorController.GenericMotorController[] controllers = new SimulatedMotorController.GenericMotorController[mapleModules.length];
		for (int i = 0; i < mapleModules.length; i++) {
			controllers[i] = mapleModules[i].useGenericMotorControllerForDrive();
		}
		return controllers;
	}

	private SimulatedMotorController.GenericMotorController[] createMapleSteerControllers(
			SwerveDriveSimulation simulation) {
		if (simulation == null) {
			return null;
		}

		SwerveModuleSimulation[] mapleModules = simulation.getModules();
		SimulatedMotorController.GenericMotorController[] controllers = new SimulatedMotorController.GenericMotorController[mapleModules.length];
		for (int i = 0; i < mapleModules.length; i++) {
			controllers[i] = mapleModules[i].useGenericControllerForSteer();
		}
		return controllers;
	}

	private void configurePhoenixSimDevices() {
		for (int i = 0; i < m_moduleConstants.length; i++) {
			SwerveModuleConstants<?, ?, ?> module = m_moduleConstants[i];
			TalonFXSimState driveSimState = getModule(i).getDriveMotor().getSimState();
			TalonFXSimState steerSimState = getModule(i).getSteerMotor().getSimState();
			CANcoderSimState encoderSimState = getModule(i).getEncoder().getSimState();

			driveSimState.Orientation = module.DriveMotorInverted
					? ChassisReference.Clockwise_Positive
					: ChassisReference.CounterClockwise_Positive;
			steerSimState.Orientation = module.SteerMotorInverted
					? ChassisReference.Clockwise_Positive
					: ChassisReference.CounterClockwise_Positive;
			encoderSimState.Orientation = module.EncoderInverted
					? ChassisReference.Clockwise_Positive
					: ChassisReference.CounterClockwise_Positive;
			encoderSimState.SensorOffset = module.EncoderOffset;
		}
		syncPhoenixSimStateFromMaple();
	}

	private void applyPhoenixOutputsToMaple() {
		double supplyVoltage = RobotController.getBatteryVoltage();
		for (int i = 0; i < m_moduleConstants.length; i++) {
			TalonFXSimState driveSimState = getModule(i).getDriveMotor().getSimState();
			TalonFXSimState steerSimState = getModule(i).getSteerMotor().getSimState();
			CANcoderSimState encoderSimState = getModule(i).getEncoder().getSimState();

			driveSimState.setSupplyVoltage(supplyVoltage);
			steerSimState.setSupplyVoltage(supplyVoltage);
			encoderSimState.setSupplyVoltage(supplyVoltage);

			m_mapleDriveControllers[i].requestVoltage(Volts.of(driveSimState.getMotorVoltage()));
			m_mapleSteerControllers[i].requestVoltage(Volts.of(steerSimState.getMotorVoltage()));
		}

		getPigeon2().getSimState().setSupplyVoltage(supplyVoltage);
	}

	private void updatePhoenixSimSignals() {
		syncPhoenixSimStateFromMaple();
		applyPhoenixOutputsToMaple();
	}

	private void syncPhoenixSimStateFromMaple() {
		if (m_mapleDriveSimulation == null) {
			return;
		}

		SwerveModuleSimulation[] mapleModules = m_mapleDriveSimulation.getModules();
		for (int i = 0; i < mapleModules.length; i++) {
			SwerveModuleSimulation mapleModule = mapleModules[i];
			TalonFXSimState driveSimState = getModule(i).getDriveMotor().getSimState();
			TalonFXSimState steerSimState = getModule(i).getSteerMotor().getSimState();
			CANcoderSimState encoderSimState = getModule(i).getEncoder().getSimState();

			driveSimState.setRawRotorPosition(mapleModule.getDriveEncoderUnGearedPosition());
			driveSimState.setRotorVelocity(mapleModule.getDriveEncoderUnGearedSpeed());
			steerSimState.setRawRotorPosition(
					mapleModule.getSteerAbsoluteAngle().times(mapleModule.config.STEER_GEAR_RATIO));
			steerSimState.setRotorVelocity(
					mapleModule.getSteerAbsoluteEncoderSpeed().times(mapleModule.config.STEER_GEAR_RATIO));
			encoderSimState.setRawPosition(mapleModule.getSteerAbsoluteAngle());
			encoderSimState.setVelocity(mapleModule.getSteerAbsoluteEncoderSpeed());
		}

		Pigeon2SimState pigeonSimState = getPigeon2().getSimState();
		Pose2d simulatedPose = m_mapleDriveSimulation.getSimulatedDriveTrainPose();
		ChassisSpeeds simulatedSpeeds = m_mapleDriveSimulation.getDriveTrainSimulatedChassisSpeedsRobotRelative();
		pigeonSimState.setRawYaw(simulatedPose.getRotation().getDegrees());
		pigeonSimState.setPitch(0.0);
		pigeonSimState.setRoll(0.0);
		pigeonSimState.setAngularVelocityZ(RadiansPerSecond.of(simulatedSpeeds.omegaRadiansPerSecond));
	}

	private Rotation2d getOdometryHeading(SwerveDriveState state) {
		if (m_mapleDriveSimulation == null) {
			return state.RawHeading;
		}

		return Rotation2d.fromDegrees(getPigeon2().getYaw().refresh().getValueAsDouble());
	}

	private double trackLengthMeters() {
		double minX = Double.POSITIVE_INFINITY;
		double maxX = Double.NEGATIVE_INFINITY;
		for (var moduleLocation : getModuleLocations()) {
			minX = Math.min(minX, moduleLocation.getX());
			maxX = Math.max(maxX, moduleLocation.getX());
		}
		return maxX - minX;
	}

	private double trackWidthMeters() {
		double minY = Double.POSITIVE_INFINITY;
		double maxY = Double.NEGATIVE_INFINITY;
		for (var moduleLocation : getModuleLocations()) {
			minY = Math.min(minY, moduleLocation.getY());
			maxY = Math.max(maxY, moduleLocation.getY());
		}
		return maxY - minY;
	}
}
