package frc.robot.constants.drive;

import static edu.wpi.first.units.Units.Amps;
import static edu.wpi.first.units.Units.Inches;
import static edu.wpi.first.units.Units.KilogramSquareMeters;
import static edu.wpi.first.units.Units.Kilograms;
import static edu.wpi.first.units.Units.Meters;
import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.Rotations;
import static edu.wpi.first.units.Units.Volts;

import java.util.function.Supplier;

import org.ironmaple.simulation.drivesims.COTS;
import org.ironmaple.simulation.drivesims.SwerveModuleSimulation;
import org.ironmaple.simulation.drivesims.configs.DriveTrainSimulationConfig;
import org.ironmaple.simulation.drivesims.configs.SwerveModuleSimulationConfig;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CANcoderConfiguration;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.StaticFeedforwardSignValue;
import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstantsFactory;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.ClosedLoopOutputType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.DriveMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerFeedbackType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerMotorArrangement;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.Current;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.units.measure.MomentOfInertia;
import edu.wpi.first.units.measure.Voltage;
import frc.robot.subsystems.drive.CommandSwerveDrivetrain;

// Generated by the 2026 Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public final class DrivetrainConstants {
	public static final double MAX_SPEED = 5.24;
	public static final double MAX_ANGULAR_RATE = 7;

	public static final double STEER_KP = 100.0;
	public static final double STEER_KI = 0.0;
	public static final double STEER_KD = 0.5;
	public static final double STEER_KS = 0.2;
	public static final double STEER_KV = 1.50;
	public static final double STEER_KA = 0.0;

	public static final double DRIVE_KP = 0.2;
	public static final double DRIVE_KI = 0.0;
	public static final double DRIVE_KD = 0.0;
	public static final double DRIVE_KS = 0.1;
	public static final double DRIVE_KV = 0.124;

	public static final CANBus CAN_BUS = new CANBus("MECO CANIvore", "./logs/example.hoot");
	public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(5.5);

	public static final double kSimRobotMassKg = 53.0;
	public static final double kSimBumperLengthMeters = 0.8509;
	public static final double kSimBumperWidthMeters = 0.8509;
	public static final double kSimWheelCoefficientOfFriction = 2.9;
	public static final double kSimFieldLengthMeters = 16.540988;
	public static final double kSimFieldWidthMeters = 8.052;
	public static final double kSimDefaultSpawnYMeters = 0.9;
	public static final double kSimResetSettleSeconds = 0.02;

	private static final Slot0Configs STEER_GAINS = createSteerGains(STEER_KP, STEER_KI, STEER_KD);
	private static final Slot0Configs DRIVE_GAINS = createDriveGains(DRIVE_KP, DRIVE_KI, DRIVE_KD);

	private static final ClosedLoopOutputType STEER_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.Voltage;
	private static final ClosedLoopOutputType DRIVE_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.Voltage;
	private static final DriveMotorArrangement DRIVE_MOTOR_TYPE = DriveMotorArrangement.TalonFX_Integrated;
	private static final SteerMotorArrangement STEER_MOTOR_TYPE = SteerMotorArrangement.TalonFX_Integrated;
	private static final SteerFeedbackType STEER_FEEDBACK_TYPE = SteerFeedbackType.FusedCANcoder;

	private static final Current SLIP_CURRENT = Amps.of(50);
	private static final TalonFXConfiguration DRIVE_INITIAL_CONFIGS = new TalonFXConfiguration().withCurrentLimits(
			new CurrentLimitsConfigs().withSupplyCurrentLimit(55).withSupplyCurrentLimitEnable(true));
	private static final TalonFXConfiguration STEER_INITIAL_CONFIGS = new TalonFXConfiguration().withCurrentLimits(
			new CurrentLimitsConfigs().withStatorCurrentLimit(Amps.of(30)).withStatorCurrentLimitEnable(true));
	private static final CANcoderConfiguration ENCODER_INITIAL_CONFIGS = new CANcoderConfiguration();
	private static final Pigeon2Configuration PIGEON_CONFIGS = null;

	private static final double COUPLE_RATIO = 4.909090909090909;
	private static final double DRIVE_GEAR_RATIO = 5.8909090909090915;
	private static final double STEER_GEAR_RATIO = 12.1;
	private static final Distance WHEEL_RADIUS = Inches.of(2);
	private static final boolean INVERT_LEFT_SIDE = false;
	private static final boolean INVERT_RIGHT_SIDE = true;
	private static final int PIGEON_ID = 13;

	private static final MomentOfInertia STEER_INERTIA = KilogramSquareMeters.of(0.01);
	private static final MomentOfInertia DRIVE_INERTIA = KilogramSquareMeters.of(0.01);
	private static final Voltage STEER_FRICTION_VOLTAGE = Volts.of(0.2);
	private static final Voltage DRIVE_FRICTION_VOLTAGE = Volts.of(0.2);

	private static final ModuleSpec FRONT_LEFT_SPEC = new ModuleSpec(1, 2, 9, Rotations.of(0.3076171875), Inches.of(11),
			Inches.of(11), INVERT_LEFT_SIDE, true, false);
	private static final ModuleSpec FRONT_RIGHT_SPEC = new ModuleSpec(3, 8, 10, Rotations.of(0.304931640625),
			Inches.of(11), Inches.of(-11), INVERT_RIGHT_SIDE, true, false);
	private static final ModuleSpec BACK_LEFT_SPEC = new ModuleSpec(5, 6, 11, Rotations.of(-0.083740234375),
			Inches.of(-11), Inches.of(11), INVERT_LEFT_SIDE, true, false);
	private static final ModuleSpec BACK_RIGHT_SPEC = new ModuleSpec(7, 4, 12, Rotations.of(-0.346435546875),
			Inches.of(-11), Inches.of(-11), INVERT_RIGHT_SIDE, true, false);

	public static final SwerveDrivetrainConstants SWERVE_DRIVETRAIN_CONSTANTS = new SwerveDrivetrainConstants()
			.withCANBusName(CAN_BUS.getName()).withPigeon2Id(PIGEON_ID).withPigeon2Configs(PIGEON_CONFIGS);

	private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> MODULE_CONSTANTS_FACTORY = new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
			.withDriveMotorGearRatio(DRIVE_GEAR_RATIO).withSteerMotorGearRatio(STEER_GEAR_RATIO)
			.withCouplingGearRatio(COUPLE_RATIO).withWheelRadius(WHEEL_RADIUS).withSteerMotorGains(STEER_GAINS)
			.withDriveMotorGains(DRIVE_GAINS).withSteerMotorClosedLoopOutput(STEER_CLOSED_LOOP_OUTPUT)
			.withDriveMotorClosedLoopOutput(DRIVE_CLOSED_LOOP_OUTPUT).withSlipCurrent(SLIP_CURRENT)
			.withSpeedAt12Volts(kSpeedAt12Volts).withDriveMotorType(DRIVE_MOTOR_TYPE)
			.withSteerMotorType(STEER_MOTOR_TYPE).withFeedbackSource(STEER_FEEDBACK_TYPE)
			.withDriveMotorInitialConfigs(DRIVE_INITIAL_CONFIGS).withSteerMotorInitialConfigs(STEER_INITIAL_CONFIGS)
			.withEncoderInitialConfigs(ENCODER_INITIAL_CONFIGS).withSteerInertia(STEER_INERTIA)
			.withDriveInertia(DRIVE_INERTIA).withSteerFrictionVoltage(STEER_FRICTION_VOLTAGE)
			.withDriveFrictionVoltage(DRIVE_FRICTION_VOLTAGE);

	public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft = createModuleConstants(
			FRONT_LEFT_SPEC);
	public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight = createModuleConstants(
			FRONT_RIGHT_SPEC);
	public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft = createModuleConstants(
			BACK_LEFT_SPEC);
	public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight = createModuleConstants(
			BACK_RIGHT_SPEC);

	public static final DriveTrainSimulationConfig SIMULATION_CONFIG = DriveTrainSimulationConfig.Default()
			.withRobotMass(Kilograms.of(kSimRobotMassKg))
			.withBumperSize(Meters.of(kSimBumperLengthMeters), Meters.of(kSimBumperWidthMeters))
			.withTrackLengthTrackWidth(Meters.of(trackLengthMeters()), Meters.of(trackWidthMeters()))
			.withGyro(COTS.ofPigeon2()).withSwerveModule(createSwerveModuleSimulationFactory());

	private DrivetrainConstants() {
	}

	public static CommandSwerveDrivetrain createDrivetrain() {
		return new CommandSwerveDrivetrain(SWERVE_DRIVETRAIN_CONSTANTS, FrontLeft, FrontRight, BackLeft, BackRight);
	}

	public static Slot0Configs createSteerGains(double kP, double kI, double kD) {
		return new Slot0Configs().withKP(kP).withKI(kI).withKD(kD).withKS(STEER_KS).withKV(STEER_KV).withKA(STEER_KA)
				.withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
	}

	public static Slot0Configs createDriveGains(double kP, double kI, double kD) {
		return new Slot0Configs().withKP(kP).withKI(kI).withKD(kD).withKS(DRIVE_KS).withKV(DRIVE_KV);
	}

	private static SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> createModuleConstants(
			ModuleSpec spec) {
		return MODULE_CONSTANTS_FACTORY.createModuleConstants(spec.steerMotorId(), spec.driveMotorId(),
				spec.encoderId(), spec.encoderOffset(), spec.xPos(), spec.yPos(), spec.driveMotorInverted(),
				spec.steerMotorInverted(), spec.encoderInverted());
	}

	private static double trackLengthMeters() {
		return Math.max(Math.abs(FRONT_LEFT_SPEC.xPos().in(Meters)), Math.abs(BACK_LEFT_SPEC.xPos().in(Meters))) * 2.0;
	}

	private static double trackWidthMeters() {
		return Math.max(Math.abs(FRONT_LEFT_SPEC.yPos().in(Meters)), Math.abs(FRONT_RIGHT_SPEC.yPos().in(Meters)))
				* 2.0;
	}

	private static Supplier<SwerveModuleSimulation> createSwerveModuleSimulationFactory() {
		DCMotor driveMotorModel = DCMotor.getKrakenX60Foc(1);
		double calibratedWheelRadiusMeters = kSpeedAt12Volts.in(MetersPerSecond)
				/ (driveMotorModel.freeSpeedRadPerSec / FrontLeft.DriveMotorGearRatio);
		SwerveModuleSimulationConfig moduleConfig = new SwerveModuleSimulationConfig(driveMotorModel,
				DCMotor.getKrakenX60Foc(1), FrontLeft.DriveMotorGearRatio, FrontLeft.SteerMotorGearRatio,
				Volts.of(FrontLeft.DriveFrictionVoltage), Volts.of(FrontLeft.SteerFrictionVoltage),
				Meters.of(calibratedWheelRadiusMeters), KilogramSquareMeters.of(FrontLeft.SteerInertia),
				kSimWheelCoefficientOfFriction);
		return () -> new SwerveModuleSimulation(moduleConfig);
	}

	private record ModuleSpec(int steerMotorId, int driveMotorId, int encoderId, Angle encoderOffset, Distance xPos,
			Distance yPos, boolean driveMotorInverted, boolean steerMotorInverted, boolean encoderInverted) {
	}

	public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
		public TunerSwerveDrivetrain(SwerveDrivetrainConstants drivetrainConstants,
				SwerveModuleConstants<?, ?, ?>... modules) {
			super(TalonFX::new, TalonFX::new, CANcoder::new, drivetrainConstants, modules);
		}

		public TunerSwerveDrivetrain(SwerveDrivetrainConstants drivetrainConstants, double odometryUpdateFrequency,
				SwerveModuleConstants<?, ?, ?>... modules) {
			super(TalonFX::new, TalonFX::new, CANcoder::new, drivetrainConstants, odometryUpdateFrequency, modules);
		}

		public TunerSwerveDrivetrain(SwerveDrivetrainConstants drivetrainConstants, double odometryUpdateFrequency,
				Matrix<N3, N1> odometryStandardDeviation, Matrix<N3, N1> visionStandardDeviation,
				SwerveModuleConstants<?, ?, ?>... modules) {
			super(TalonFX::new, TalonFX::new, CANcoder::new, drivetrainConstants, odometryUpdateFrequency,
					odometryStandardDeviation, visionStandardDeviation, modules);
		}
	}
}
